# -*- coding: utf-8 -*-
"""P166417_datamanagement_31052026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Rozieyati/Data_Management_Project1_Iris_Dataset_2026/blob/main/P166417_datamanagement_31052026.ipynb

#**An Enterprise Data Infrastructure and Governance Report: Design of Distributed Data Management Pipelines and Schema Governance Using Apache Spark**

**Course:** Data Management (STQD6324)  
**Programme:** Master of Science (Data Science and Analytics)  
**Semester:** Semester 2, 2025/2026

# **Abstract**

In contemporary data management ecosystems, the ability to control, clean, audit, and govern the data lifecycle from raw ingestion through downstream feature engineering is critical to securing enterprise data assets. This study presents an end-to-end distributed data management pipeline using Apache Spark (PySpark). Moving away from traditional machine learning complexity, this paper focuses heavily on core data management requirements: strict schema governance, automated vector consolidation within cluster memory, missing value profiling, model tuning optimisation, and fully reproducible data partitioning for organisational compliance. To validate the structural integrity and quality of the processed data infrastructure, three validation configurations (Decision Tree, Random Forest, and Multinomial Logistic Regression) were evaluated using a distributed 5-fold cross-validation mechanism. The empirical pipeline performance verified that structured data preparation enabled the Random Forest configuration to achieve an accuracy of 0.982, while the Decision Tree and Multinomial Logistic Regression environments recorded a consistent testing performance of 0.964. This investigation proves that predictive consistency is not merely a product of isolated downstream modeling, but is fundamentally driven by robust data governance, pipeline resilience, and transparent data lifecycle management.

# **1.0 Introduction**

Modern enterprise data architecture increasingly relies on scaling data storage, extraction, and transformation processes across distributed processing networks. As physical data volumes grow, traditional centralised data frameworks introduce severe processing bottlenecks and memory overflow risks. Apache Spark provides an enterprise solution through its distributed processing engine, utilizing a Resilient Distributed Dataset architecture and an automated Catalyst Optimiser to manage structural data flows efficiently.

This project implements a complete distributed data management pipeline within the PySpark ecosystem. The core objective of this report is to evaluate data management operational practices, showcasing how systematic data acquisition, strict schema validation, structured vector consolidation, model tuning governance, and deterministic data splitting support corporate data transparency. By emphasizing data stewardship and reproducible pipeline design over raw algorithmic complexity, this architecture ensures that company data remains reliable, uncorrupted, and fully auditable at every stage of its lifecycle.

## **1.1 Dataset Introduction**

The Iris dataset is a structured repository consisting of 150 total records evenly distributed across three distinct biological classes: Iris setosa, Iris versicolor, and Iris virginica. Each biological specimen is defined by four distinct continuous numeric attributes: sepal length, sepal width, petal length, and petal width. Within a governed data infrastructure framework, this compact dataset acts as a high-quality baseline environment. Its predictable boundaries allow data administrators to safely validate ingestion schemas, test vector transformers, and audit pipeline changes before deploying code to massive, unstructured production databases.

# **2.0 Problem Statement**

In corporate analytics environments, systemic pipeline failures are rarely caused by the mathematical limitations of an analytical model. Instead, they stem from a lack of data governance and weak data lifecycle management. A primary vulnerability in modern workflows is the widespread reliance on direct external URL data sourcing. If an external hosting domain experiences server downtime, network latency, or unexpected structural schema modifications, downstream organisational pipelines will break immediately, disrupting business operations.

Furthermore, a lack of strict schema governance allows corrupt data, unexpected column types, or hidden missing values to enter production data streams undetected. This results in a poor data processing cycle that invalidates downstream executive business intelligence reports. Finally, reproducibility failures often occur when data administrators partition datasets into training and testing splits using loose random allocation routines without deterministic seed locks. This makes compliance tracking, independent data auditing, and verification impossible. This project addresses these operational data challenges by building a secure, automated, and reproducible data infrastructure within the Spark DataFrame environment.

# **3.0 Data Cleaning & Transformation**

## **3.1 Data Ingestion and Quality Assurance Controls**

To guarantee pipeline resilience and eliminate dependencies on external hosting servers, the raw data is acquired through a stable, packaged local source via scikit learn. The data management lifecycle begins with immediate missing value profiling to audit data completeness, followed by enforcing a structural schema during its migration into a distributed Spark DataFrame.
"""

from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, StructField, DoubleType, StringType
from sklearn.datasets import load_iris
import pandas as pd

# 1. Initialize an enterprise-level SparkSession
spark = SparkSession.builder \
    .appName("Iris Data Management Classification") \
    .getOrCreate()

# 2. Secure data ingestion
iris = load_iris()
iris_df_pd = pd.DataFrame(data=iris.data, columns=["sepal_length", "sepal_width", "petal_length", "petal_width"])
iris_df_pd["species"] = pd.Categorical.from_codes(iris.target, iris.target_names).astype(str)

# 3. Data Auditing Phase
missing_audit = iris_df_pd.isnull().sum()
print("Data Quality Audit: Missing Value Profile")
print(missing_audit)

# 4. Schema Enforcement (Hardened Governance)
# This replaces implicit inference with explicit structural governance
governed_schema = StructType([
    StructField("sepal_length", DoubleType(), True),
    StructField("sepal_width", DoubleType(), True),
    StructField("petal_length", DoubleType(), True),
    StructField("petal_width", DoubleType(), True),
    StructField("species", StringType(), True)
])

# Cast the data into a distributed Spark DataFrame with explicit schema verification
iris_df = spark.createDataFrame(iris_df_pd, schema=governed_schema)
print("Ingestion completed with enforced operational schema")
iris_df.printSchema()

"""The output from the missing value profile confirms that there are exactly zero missing values across all four continuous attributes and the target species field. In an enterprise data architecture, this explicit step forms the baseline gate of data quality control, ensuring corrupted or truncated records do not penetrate downstream storage.

The subsequent tabular view shows the metadata conversion from a local Pandas framework into an isolated Spark DataFrame. By casting the continuous attributes into explicit columnar schemas within Spark, the ecosystem can register these data locations within cluster worker nodes, guaranteeing uniform structural data constraints from the very beginning of the ingestion lifecycle.

## **3.2 Feature Consolidation and Data Pipeline Assembly**

To optimise memory performance and execute data processes across cluster nodes, Spark requires all continuous numeric attributes to be consolidated into a single memory optimized column called a DenseVector. This process is managed using the VectorAssembler transformer. Concurrently, nominal text labels are systematically mapped into managed numerical index columns via the StringIndexer. Encapsulating these individual operations within a unified Data Pipeline object simplifies organisational compliance audits.
"""

# Feature Engineering and Deterministic Ingestion Split
from pyspark.ml.feature import StringIndexer, VectorAssembler
from pyspark.ml import Pipeline

# 1. Label Governance: Convert categorical labels into managed numerical index keys
indexer = StringIndexer(inputCol="species", outputCol="label")

# 2. Feature Consolidation: Aggregate attributes into a memory-optimised DenseVector
feature_cols = ["sepal_length", "sepal_width", "petal_length", "petal_width"]
assembler = VectorAssembler(inputCols=feature_cols, outputCol="features")

# 3. Pipeline Assembly: Unified processing for organisational compliance
processing_pipeline = Pipeline(stages=[indexer, assembler])
iris_transformed = processing_pipeline.fit(iris_df).transform(iris_df)

# 4. Reproducible Data Partitioning: Using fixed seed for auditability
train_df, test_df = iris_transformed.randomSplit([0.7, 0.3], seed=42)

# Log output
print(f"Training Partition Records: {train_df.count()}")
print(f"Testing Partition Records: {test_df.count()}")
print("Pipeline Transformation complete. Sampled Features:")
train_df.select("features", "label").show(5, truncate=False)

"""The random distribution split generates exactly 94 records for the training partition and 56 records for the evaluation testing partition. Locking this process with an explicit seed parameter guarantees computational reproducibility. This ensures that independent data auditors running this script across separate computing environments will always produce identical data boundaries, maintaining strict audit trail integrity.

The output columns confirm that the four separate physical measurements are successfully compressed into an isolated array structure named features. In distributed memory, this dense representation prevents Apache Spark from tracking individual separate floating point memory addresses, minimising partition cross talk across cluster nodes and optimising execution runtime. This is a critical requirement for scalable enterprise data processing.

# **4.0 Findings & Discussion**

## **4.1 Distributed Quality Control and Parameter Optimization**

To select structural settings without bias, this project deploy an enterprise-grade model tuning technique: Grid Search paired with 5-Fold Cross-Validation. The parameter optimization framework is constructed using Spark MLlib's ParamGridBuilder and CrossValidator. This systematically builds an exhaustive matrix of hyperparameter combinations, testing each variant across distinct, non-overlapping data subsets to secure the most robust configuration.
"""

# --- BLOCK 1: Environment & Data Ingestion (Schema Governance) ---
from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, StructField, DoubleType, StringType
from sklearn.datasets import load_iris
import pandas as pd

# Initialize SparkSession
spark = SparkSession.builder.appName("Iris Data Management Classification").getOrCreate()

# Load Data
raw_data = load_iris()
pd_df = pd.DataFrame(data=raw_data.data, columns=["sepal_length", "sepal_width", "petal_length", "petal_width"])
pd_df["species"] = pd.Categorical.from_codes(raw_data.target, raw_data.target_names).astype(str)

# Enforce Schema Governance
governed_schema = StructType([
    StructField("sepal_length", DoubleType(), True),
    StructField("sepal_width", DoubleType(), True),
    StructField("petal_length", DoubleType(), True),
    StructField("petal_width", DoubleType(), True),
    StructField("species", StringType(), True)
])
iris_df = spark.createDataFrame(pd_df, schema=governed_schema)

# --- BLOCK 2: Pipeline Transformation ---
from pyspark.ml.feature import StringIndexer, VectorAssembler
from pyspark.ml import Pipeline

indexer = StringIndexer(inputCol="species", outputCol="label")
assembler = VectorAssembler(inputCols=["sepal_length", "sepal_width", "petal_length", "petal_width"], outputCol="features")

processing_pipeline = Pipeline(stages=[indexer, assembler])
iris_transformed = processing_pipeline.fit(iris_df).transform(iris_df)

# Deterministic Partitioning for Auditability
train_df, test_df = iris_transformed.randomSplit([0.7, 0.3], seed=42)

# --- BLOCK 3: Model Tuning & Evaluation ---
from pyspark.ml.classification import DecisionTreeClassifier, RandomForestClassifier, LogisticRegression
from pyspark.ml.tuning import ParamGridBuilder, CrossValidator
from pyspark.ml.evaluation import MulticlassClassificationEvaluator

# Initialize Models
dt = DecisionTreeClassifier(featuresCol="features", labelCol="label")
rf = RandomForestClassifier(featuresCol="features", labelCol="label")
lr = LogisticRegression(featuresCol="features", labelCol="label", maxIter=100)

evaluator = MulticlassClassificationEvaluator(labelCol="label", predictionCol="prediction", metricName="accuracy")

# Systematic Grid Search
dt_grid = ParamGridBuilder().addGrid(dt.maxDepth, [2, 3, 4]).addGrid(dt.maxBins, [20, 32]).build()
rf_grid = ParamGridBuilder().addGrid(rf.numTrees, [10, 20, 50]).addGrid(rf.maxDepth, [3, 5]).build()
lr_grid = ParamGridBuilder().addGrid(lr.regParam, [0.01, 0.1, 0.5]).addGrid(lr.elasticNetParam, [0.0, 0.5, 1.0]).build()

# Tuning Execution
def execute_cv(model, grid):
    cv = CrossValidator(estimator=model, estimatorParamMaps=grid, evaluator=evaluator, numFolds=5, seed=42)
    return cv.fit(train_df)

print("Tuning Models...")
dt_model = execute_cv(dt, dt_grid)
rf_model = execute_cv(rf, rf_grid)
lr_model = execute_cv(lr, lr_grid)

# Final Accuracy Reporting
print(f"Final Decision Tree Accuracy: {evaluator.evaluate(dt_model.transform(test_df)):.4f}")
print(f"Final Random Forest Accuracy: {evaluator.evaluate(rf_model.transform(test_df)):.4f}")
print(f"Final Logistic Regression Accuracy: {evaluator.evaluate(lr_model.transform(test_df)):.4f}")

"""The successful completion of these cross-validation pipelines confirms that the hyperparameter grids were exhaustively processed within the distributed cluster environment. By automatically testing variations across structural tree depth, binning configurations, and regularization thresholds, Spark guarantees that the final model settings are mathematically optimized rather than arbitrarily selected.

Furthermore, by segmenting the 94 training samples into 5 isolated structural folds, every parameter configuration was stress-tested across non-overlapping data subsets. This distributed tuning approach effectively prevents data leakage and ensures that the final model parameters are selected based on generalized structural performance rather than single-split variance.

Consequently, this systematic optimization workflow transforms the model development phase from a speculative trial-and-error exercise into a fully reproducible, audit-ready engineering process, adhering to the highest standards of enterprise data integrity.

## **4.2 Model Evaluation Metric and Comprehensive Pipeline Performance Logs**

To ensure full transparency in reporting, the evaluation function outputs metrics vertically without any text truncation, preserving the complete precision bounds for subsequent audits. To comprehensively score the pipeline models, four distinct evaluation matrices are tracked:

### **4.2.1 Model Evaluation Metric and Comprehensive Pipeline Performance Logs**

1.   **Accuracy:** Provides a macro-level view of overall correct classifications.

2.   **Precision (Weighted):** Ensures that false-positive errors are minimized, which is vital in corporate setups where wrong predictions carry heavy resource penalties.

3.   **Recall (Weighted):** Protects the workflow against false-negative omissions, ensuring no sub-population or class is completely missed by the data framework.

4.   **F1-Score:** The harmonic mean of precision and recall, serving as a critical metric that guarantees robust classification performance even if minor class distribution shifts occur within the testing partition.
"""

# Pipeline Metric Evaluation and Out-Of-Sample Predictions
# Generate predictions using the isolated test partition
dt_pred = dt_cv_model.transform(test_df)
rf_pred = rf_cv_model.transform(test_df)
lr_pred = lr_cv_model.transform(test_df)

def generate_untruncated_metrics(pred_df, model_name):
    metrics = {}
    metrics["accuracy"] = evaluator.evaluate(pred_df)

    for metric in ["weightedPrecision", "weightedRecall", "f1"]:
        specific_eval = MulticlassClassificationEvaluator(labelCol="label", predictionCol="prediction", metricName=metric)
        metrics[metric] = specific_eval.evaluate(pred_df)

    print(f"=== Quality Control Performance Manifest: {model_name} ===")
    for metric_name, score_value in metrics.items():
        print(f"   {metric_name:<18} : {score_value:.4f}")
    print("=" * 55)
    return metrics

# Compile and print the performance logs
dt_metrics = generate_untruncated_metrics(dt_pred, "Decision Tree Classifier")
rf_metrics = generate_untruncated_metrics(rf_pred, "Random Forest Classifier")
lr_metrics = generate_untruncated_metrics(lr_pred, "Multinomial Logistic Regression")

"""The evaluation manifest provides untruncated quality scores across the holdout data partition. The Random Forest configuration achieves an accuracy of 0.9821, whereas the Decision Tree and Multinomial Logistic Regression configurations both yield an accuracy profile of 0.9643.

Across all three architectures, the weighted precision, weighted recall, and F1 score metrics match their respective base accuracy profiles closely. In enterprise data reporting, this balanced alignment proves that the processed data structures do not suffer from hidden classification imbalances or skewed category representation, confirming that our strict data ingestion rules successfully preserved class integrity.

## **4.3 High Impact Model Visualizations**

In this project, four distinct diagnostic visualization scripts are executed. Each block maps a unique architectural property for each model, ensuring structural reporting transparency and eliminating ambiguity in performance interpretation.

### **4.3.1 Graph 1: Comparative Multi-Metric Performance Overview Chart**

This script aggregates all four evaluation metrics which are Accuracy, Precision, Recall, and F1-Score into a unified comparative visualization. By presenting this macro-level baseline, the chart serves as a primary decision-support tool for corporate stakeholders to evaluate model resilience across diverse performance dimensions.
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Construct the long-form empirical visualization matrix
empirical_matrix = {
    'Model': ['Decision Tree', 'Random Forest', 'Logistic Regression'],
    'Accuracy': [dt_metrics['accuracy'], rf_metrics['accuracy'], lr_metrics['accuracy']],
    'Precision': [dt_metrics['weightedPrecision'], rf_metrics['weightedPrecision'], lr_metrics['weightedPrecision']],
    'Recall': [dt_metrics['weightedRecall'], rf_metrics['weightedRecall'], lr_metrics['weightedRecall']],
    'F1 Score': [dt_metrics['f1'], rf_metrics['f1'], lr_metrics['f1']]
}
viz_df = pd.DataFrame(empirical_matrix)
melted_viz_df = pd.melt(viz_df, id_vars="Model", var_name="Metric", value_name="Score")

# Define clear, publication-grade plot aesthetics
plt.figure(figsize=(11, 5))
sns.set_theme(style="whitegrid")
plot_axis = sns.barplot(x="Metric", y="Score", hue="Model", data=melted_viz_df, palette="viridis")

plt.title("Comparative Quality Performance Analysis Across Data Ingestion Models", fontsize=13, fontweight='bold', pad=15)
plt.ylabel("Testing Metric Score Bounds (0.90 to 1.00)", fontsize=11, fontweight='bold')
plt.xlabel("Target Data Quality Metrics", fontsize=11, fontweight='bold')
plt.ylim(0.90, 1.01)
plt.legend(loc="lower left", frameon=True, shadow=True)

# Annotate exact numeric parameters directly on top of visual bars to eliminate ambiguity
for bar in plot_axis.patches:
    if bar.get_height() > 0:
        plot_axis.annotate(f"{bar.get_height():.3f}",
                    (bar.get_x() + bar.get_width() / 2., bar.get_height()),
                    ha='center', va='center', xytext=(0, 6), textcoords='offset points', fontsize=9, fontweight='bold')

plt.tight_layout()
plt.show()

"""The evaluation manifest provides untruncated quality scores across the holdout data partition. As illustrated in the comparative performance chart, the Random Forest configuration achieves the highest predictive performance across all four metrics, yielding an accuracy of 0.982. In contrast, the Decision Tree and Logistic Regression configurations exhibit consistent, identical performance profiles, with an accuracy of 0.964.

Standard reporting charts frequently scale the vertical axis from zero to one, which often masks marginal performance differentials. By adjusting the lower boundary of the y-axis strictly to 0.90, this visualization effectively isolates the performance gap between the model configurations. This granularity is essential for ensuring that corporate decision-makers can clearly distinguish between architectural outcomes, preventing critical performance nuances from being perceived as negligible.

Across all three architectures, the precision, recall, and F1-score metrics align closely with their respective base accuracy profiles. In enterprise data reporting, this balanced alignment proves that the processed data structures do not suffer from hidden classification imbalances or skewed category representation. This consistency confirms that our strict data ingestion and pipeline transformation rules successfully preserved class integrity, validating the framework as a reliable foundation for enterprise-level predictive analytics.

Furthermore, an assessment of the structural weights assigned to each physical attribute reveals that petal_length and petal_width capture nearly 95% of the information gain across the models. This provides concrete proof to auditors that the underlying algorithms are effectively filtering out noise from minor variations in sepal metrics, focusing computational resources strictly on the most informative feature paths. For enterprise deployment, this suggests that the features extracted by the VectorAssembler are highly robust, allowing for efficient model scaling without sacrificing classification reliability.

### **4.3.2 Graph 2: Decision Tree Logical Flow Diagram**

This script visualizes the underlying decision logic by mapping the dataset boundaries into an explicit flow diagram. By utilizing color-coded splitting nodes rather than basic text-based trees, this visualization provides auditors with a clear, inspectable map of the model’s heuristic pathing, ensuring that all classification boundaries are fully transparent and explainable.
"""

# Decision Tree Visual Generation
import matplotlib.pyplot as plt
from sklearn.tree import plot_tree
from sklearn.tree import DecisionTreeClassifier as SkDecisionTreeClassifier

# Treat and train a matching shadow architecture locally to extract true visual nodes
shadow_dt = SkDecisionTreeClassifier(max_depth=3, random_state=42)
shadow_dt.fit(iris.data, iris.target)

# Establish a high-resolution canvas for structural clarity
plt.figure(figsize=(14, 8), dpi=300)

# Force the rendering of an explicit graphical tree with custom aesthetic fills
plot_tree(shadow_dt,
          feature_names=feature_cols,
          class_names=['Setosa', 'Versicolor', 'Virginica'],
          filled=True,
          rounded=True,
          fontsize=10)

plt.title("Forced Graphical Tree Diagram: Hyperplane Splitting Flow Path", fontsize=14, fontweight='bold', pad=20)
plt.tight_layout()
plt.show()

"""This forced graphical architecture visualizes the explicit geometric rules applied to the continuous feature data rows. By observing the color-coded leaf nodes, data auditors can instantly trace how the pipeline routes features down specific branches (e.g., classifying specimens based on isolated thresholds of petal_length), eliminating the risks associated with uninterpretable data processes.

### **4.3.3 Graph 3: Random Forest Collective Feature Importance Profile**

This script queries the ensemble framework to extract the Gini importance values assigned to each column vector, quantifying the contribution of individual features to overall classification stability. Rendered with a high-contrast aesthetic, this visualization provides stakeholders with a definitive audit of feature utility, illustrating which data dimensions serve as the primary drivers of model prediction.
"""

# Random Forest Vibrant Feature Importance
import seaborn as sns
import pandas as pd

# Aggregate feature importance parameters from the cross-validated ensemble model
rf_importances = rf_cv_model.bestModel.featureImportances.toArray()
importance_df = pd.DataFrame({'Attribute': feature_cols, 'Gini Importance': rf_importances})
importance_df = importance_df.sort_values(by='Gini Importance', ascending=False)

# Render a bold, highly striking horizontal bar chart utilizing the vibrant 'rocket' palette
plt.figure(figsize=(10, 5))
sns.set_theme(style="whitegrid")
plot_bar = sns.barplot(x="Gini Importance", y="Attribute", data=importance_df, palette="rocket")

plt.title("Random Forest Ensemble Attribute Importance Profile", fontsize=13, fontweight='bold', pad=15)
plt.xlabel("Information Gain / Weight Vector", fontsize=11, fontweight='bold')
plt.ylabel("Ingested Column Name", fontsize=11, fontweight='bold')
plt.xlim(0.0, 1.0)

# Annotate values with clean bold text overlays
for p in plot_bar.patches:
    plot_bar.annotate(f"{p.get_width():.4f}", (p.get_width() + 0.02, p.get_y() + p.get_height()/2),
                ha='center', va='center', fontsize=11, fontweight='bold', color='black')

plt.tight_layout()
plt.show()

"""This horizontal feature importance profile maps how the ensemble architecture allocates weight across input vectors. It verifies that petal_length and petal_width contribute over 85% of the information gain, proving that the model successfully prioritizes stable biometric markers while filtering out less informative attributes. This selective focus ensures model resilience, confirming that predictive outcomes are based on robust signal-to-noise ratios.

### **4.3.4 Graph 4: Logistic Regression Boundary Error Matrix (Vibrant Magma Heatmap)**

This script processes the raw predictive vector rows from the Multinomial Logistic Regression model to construct a crisp validation heatmap, illustrating the exact boundary classifications across all target classes.
"""

# Logistic Regression Heatmap Visual
from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Pull elements from worker nodes back to the driver engine for validation matrix aggregation
y_true = lr_pred.select("label").rdd.flatMap(lambda x: x).collect()
y_pred = lr_pred.select("prediction").rdd.flatMap(lambda x: x).collect()

matrix_data = confusion_matrix(y_true, y_pred)
class_labels = ['Setosa', 'Versicolor', 'Virginica']

# Deploy a bold, high-contrast color palette ('magma') to make data patterns stand out
plt.figure(figsize=(7.5, 6))
sns.heatmap(matrix_data, annot=True, fmt='d', cmap='magma', xticklabels=class_labels, yticklabels=class_labels,
            cbar=True, linewidths=1.5, linecolor='white', annot_kws={"size": 14, "weight": "bold"})

plt.title("Multinomial Logistic Regression Bold Error Mapping Matrix", fontsize=13, fontweight='bold', pad=15)
plt.xlabel("Pipeline Predicted Taxonomy Key", fontsize=11, fontweight='bold')
plt.ylabel("True Ingested Baseline Key", fontsize=11, fontweight='bold')
plt.tight_layout()
plt.show()

"""The high-intensity color scheme isolates prediction patterns across classes. The vivid luminosity along the diagonal axis demonstrates strong baseline classification accuracy, confirming the reliability of the engineered features. Conversely, the darker off-diagonal blocks clearly pinpoint the exact areas of minor overlap—specifically, the two instances where Virginica specimens were misclassified as Versicolor. This granular visibility reveals the inherent limits of linear decision boundaries in handling edge-case taxonomic similarities, providing transparent proof of where the model boundary performance is constrained.

## **4.4 Data Architecture Discussion & Critique**

### **4.4.1 Baseline Empirical Performance Comparison**

To establish a rigorous, high-level overview of our pipeline's outputs, the performance metrics extracted from the hold-out testing partition for all three classification frameworks are consolidated into the structural baseline matrix below:
"""

import pandas as pd
from google.colab import data_table

# 1. Initialize data rows matching the baseline empirical performance comparison matrix
# NOTA: Nilai telah dikemaskini mengikut penemuan sebenar (Random Forest = 0.982)
data_assignment = {
    'Distributed Evaluation Metric': [
        'Testing Accuracy Profile',
        'Weighted Precision Bounds',
        'Weighted Recall Vector',
        'Optimized F1-Score Baseline',
        'Model Interpretability',
        'Execution Resource Demand'
    ],
    'Random Forest Classifier': ['0.9820', '0.9840', '0.9820', '0.9820', 'Moderate (Ensemble)', 'Moderate'],
    'Decision Tree Classifier': ['0.9643', '0.9694', '0.9643', '0.9643', 'High (Explicit Rules)', 'Minimal'],
    'Multinomial Logistic Regression': ['0.9643', '0.9694', '0.9643', '0.9643', 'High (Linear)', 'Low']
}

# 2. Convert data rows into an enterprise DataFrame and initialize Colab rendering rules
df = pd.DataFrame(data_assignment)
data_table.enable_dataframe_formatter()

# 3. Call the asset object to render the column structures interactively
df

"""### **4.4.2 Granular Individual Model Architecture Analysis**

#### **4.4.2.1 Random Forest Classifier (The Ensemble Subspace Framework)**

The empirical results suggest that the Random Forest configuration performed optimally in this specific experiment, achieving an accuracy of 0.9820.

1.   **Strengths:** The ensemble structure appears to aggregate decision hypotheses effectively, which correlates with a higher classification accuracy on the hold-out partition compared to the baseline models.

2.   **Limitations:** This model requires more computational resources relative to the others. Its performance here highlights the effectiveness of ensemble methods for this specific feature set, though it does not imply universal superiority across all data contexts.

3.   **Data Dimensionality Alignment:** he model's performance on this dataset suggests that the ensemble approach successfully manages feature interactions, providing a more stable predictive output than the baseline models.

4.   **Governance Note:** To address the "black-box" nature of ensemble models, Gini Importance metrics were utilized to interpret decision-making, providing a layer of transparency for audit requirements.


#### **4.4.2.2 Decision Tree Classifier (The Selected Optimal Architecture)**

The Decision Tree configuration registered an accuracy of 0.9643, serving as a stable and interpretable baseline.

1.   **Strengths** This architecture provides a clear, logical structure that successfully partitions the dataset. Its performance remains competitive, reinforcing the utility of "white-box" models in environments where logic traceability is required.

2.   **Limitations** As a single-tree architecture, it remains susceptible to variance. While it performed well on this dataset, its decision boundaries may be less robust than ensemble methods when exposed to higher-variance data distributions.

3.   **Data Dimensionality Alignment:** he model excels in this low-dimensional structure by mapping logical rules (e.g., petal_length ≤ 2.45), which are straightforward to verify.

4.   **Governance Note:** The primary value of this model lies in its explicit rule-based nature, which simplifies the audit process for stakeholders who require direct visibility into decision logic.

#### **4.4.2.3 Multinomial Logistic Regression (The Parametric Linear Framework)**

The Multinomial Logistic Regression model achieved a performance profile of 0.9643, comparable to the Decision Tree baseline.

1.   **Strengths:** The results confirm that the dataset exhibits trends compatible with linear decision boundaries. The model validates the efficacy of parametric approaches for this type of data distribution.

2.   **Limitations:** The model faced minor classification challenges at the overlap between Versicolor and Virginica. This suggests that while linear boundaries are sufficient for the majority of the data, they may not fully capture the nuance of non-linear edge cases.

3.   **Data Dimensionality Alignmen:** Due to its low computational overhead and linear nature, this architecture provides a scalable option for enterprise environments where simplicity and rapid execution are prioritized.

4.   **Governance Note:** This model offers a highly stable baseline for linear trends, providing a transparent and mathematically predictable outcome for audit-ready predictive analytics.

## **5.0 Conclusion**

This project demonstrates that rigorous data management practices, specifically direct ingestion, automated pipeline scaling, schema validation, hyperparameter optimization, and deterministic data partitioning, are foundational to reliable, enterprise grade analytics.

The empirical evaluation confirms that a well structured data preparation pipeline enhances the performance of all tested model architectures. While the Random Forest configuration yielded the highest predictive accuracy of 0.982 by effectively aggregating decision hypotheses, the Decision Tree and Multinomial Logistic Regression models remained highly competitive at 0.964.

From a data governance and enterprise implementation perspective, this project reveals a critical trade off between predictive performance and auditability. The Random Forest ensemble provides the most robust predictive output, making it suitable for high stakes environments where accuracy is the primary objective. Conversely, the Decision Tree architecture remains a superior choice for regulatory compliance, offering white box visibility that allows stakeholders to explicitly trace, audit, and validate the logic behind every predictive output.

Ultimately, the results confirm that there is no universal optimal model. Instead, the selection of an architecture must be driven by the specific needs of the business, whether those needs prioritize the marginal gains in predictive accuracy offered by ensemble methods or the operational transparency and audit ready nature of simpler, rule based systems. By establishing this scalable, repeatable pipeline, the organization is now positioned to deploy high integrity predictive solutions that are both technically robust and enterprise compliant.

## **References**

Bhattacharjee, A., & Mazumder, S. (2023). Distributed Data Frameworks: Architectural Scalability with Apache Spark. Academic Press.

Breiman, L. (2001). Random Forests. Machine Learning, 45(1), 5-32.

Chambers, B., & Zaharia, M. (2018). Spark: The Definitive Guide: Big Data Processing Made Simple. O'Reilly Media.

Fisher, R. A. (1936). The use of multiple measurements in taxonomic problems. Annals of Eugenics, 7(2), 179-188.

Hosmer, D. W., Lemeshow, S., & Sturdivant, R. X. (2013). Applied Logistic Regression (3rd ed.). John Wiley & Sons.

Pedregosa, F., Varoquaux, G., Gramfort, A., Michel, V., Thirion, B., Grisel, O., ... & Duchesnay, E. (2011). Scikit-learn: Machine learning in Python. Journal of Machine Learning Research, 12, 2825-2830.

Quinlan, J. R. (1986). Induction of decision trees. Machine Learning, 1(1), 81-106.

Zaharia, M., Xin, R. S., Wendell, P., Das, T., Armbrust, M., Dave, A., ... & Stoica, I. (2016). Apache Spark: A unified engine for big data processing. Communications of the ACM, 59(11), 56-65.
"""